apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: flyte
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: flyte
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
      app.kubernetes.io/instance: flyte
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
        app.kubernetes.io/instance: flyte
    spec:
      containers:
        - image: "ecr.flyte.org/bitnami/minio:2021.10.13-debian-10-r0"
          imagePullPolicy: "IfNotPresent"
          name: minio
          env:
            - name: MINIO_ACCESS_KEY
              value: minio
            - name: MINIO_SECRET_KEY
              value: miniostorage
            - name: MINIO_DEFAULT_BUCKETS
              value: my-s3-bucket
          ports:
            - containerPort: 9000
              name: minio
            - containerPort: 9001
              name: minio-console
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 128Mi
          volumeMounts:
            - name: minio-storage
              mountPath: /data
      volumes:
        - name: minio-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: flyte
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: flyte
spec:
  type: LoadBalancer
  ports:
    - name: minio
      nodePort: 30084
      port: 9000
      protocol: TCP
      targetPort: minio
    - name: minio-console
      nodePort: 30088
      port: 9001
      protocol: TCP
      targetPort: minio-console
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: flyte
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: flyte
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: flyte
    helm.sh/chart: flyte-v0.1.10
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: postgres
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: flyte

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: flyte
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: flyte
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/instance: flyte
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/instance: flyte
    spec:
      containers:
        - image: "ecr.flyte.org/ubuntu/postgres:13-21.04_beta"
          imagePullPolicy: "IfNotPresent"
          name: postgres
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_DB
              value: flyteadmin
          ports:
            - containerPort: 5432
              name: postgres
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 128Mi
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
